from PySide6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(207, 357)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.AssetGroupBox = QtWidgets.QGroupBox(Form)
        self.AssetGroupBox.setObjectName("AssetGroupBox")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.AssetGroupBox)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.comboBox = QtWidgets.QComboBox(self.AssetGroupBox)
        self.comboBox.setObjectName("comboBox")
        self.verticalLayout_5.addWidget(self.comboBox)
        self.verticalLayout_3.addWidget(self.AssetGroupBox)
        self.tabWidget = QtWidgets.QTabWidget(Form)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.tab)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.listWidget = QtWidgets.QListWidget(self.tab)
        self.listWidget.setObjectName("listWidget")
        self.verticalLayout_4.addWidget(self.listWidget)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.tab_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.save_guides_button = QtWidgets.QPushButton(self.tab_2)
        self.save_guides_button.setObjectName("save_guides_button")
        self.verticalLayout.addWidget(self.save_guides_button)
        self.save_shapes_button = QtWidgets.QPushButton(self.tab_2)
        self.save_shapes_button.setObjectName("save_shapes_button")
        self.verticalLayout.addWidget(self.save_shapes_button)
        self.load_shapes_button = QtWidgets.QPushButton(self.tab_2)
        self.load_shapes_button.setObjectName("load_shapes_button")
        self.verticalLayout.addWidget(self.load_shapes_button)
        self.save_skin_button = QtWidgets.QPushButton(self.tab_2)
        self.save_skin_button.setObjectName("save_skin_button")
        self.verticalLayout.addWidget(self.save_skin_button)
        self.load_skin_button = QtWidgets.QPushButton(self.tab_2)
        self.load_skin_button.setObjectName("load_skin_button")
        self.verticalLayout.addWidget(self.load_skin_button)
        self.groupBox = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.save_reference_file_btn = QtWidgets.QPushButton(self.groupBox)
        self.save_reference_file_btn.setObjectName("save_reference_file_btn")
        self.verticalLayout_6.addWidget(self.save_reference_file_btn)
        self.file_name_lineEdit = QtWidgets.QLineEdit(self.groupBox)
        self.file_name_lineEdit.setObjectName("file_name_lineEdit")
        self.verticalLayout_6.addWidget(self.file_name_lineEdit)
        self.verticalLayout.addWidget(self.groupBox)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.tabWidget.addTab(self.tab_2, "")
        self.verticalLayout_3.addWidget(self.tabWidget)

        self.retranslateUi(Form)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.AssetGroupBox.setTitle(_translate("Form", "Asset build"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Form", "build steps"))
        self.save_guides_button.setToolTip(_translate("Form", "saves mgear guides"))
        self.save_guides_button.setText(_translate("Form", "save mgear guides"))
        self.save_shapes_button.setToolTip(_translate("Form", "save the shapes of selected objects"))
        self.save_shapes_button.setText(_translate("Form", "save shapes"))
        self.load_shapes_button.setToolTip(_translate("Form", "load shapes on selected objects"))
        self.load_shapes_button.setText(_translate("Form", "load shapes"))
        self.save_skin_button.setToolTip(_translate("Form", "saves the skinning of selected objects."))
        self.save_skin_button.setText(_translate("Form", "save skinning"))
        self.load_skin_button.setToolTip(_translate("Form", "loads skinning of selected objects."))
        self.load_skin_button.setText(_translate("Form", "load skinning"))
        self.groupBox.setTitle(_translate("Form", "Reference file"))
        self.save_reference_file_btn.setText(_translate("Form", "save reference file"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Form", "save data"))
